config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :covid_forms
  resources :covid_forms, path: '/', param: :id, only: %i[show]
  resources :dashboards,  only:[:show]
  get 'dashboards/show'
  get 'pages/not_here'
  get 'pages/team_records'
  resources :flags
  resources :log_dates

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/covid_form.rb
class CovidForm < ApplicationRecord
  belongs_to :user
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/drink.rb
class Drink < ApplicationRecord
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :user
  belongs_to :log_date
  belongs_to :covid_form
end

app/models/log_date.rb
class LogDate < ApplicationRecord
  belongs_to :user
  has_many :flags
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :identity, presence: true
  validates :identity, uniqueness: true
  has_many :log_dates

  has_many :covid_forms
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:identity]

 protected

 def email_required?
  false
 end


def email_changed?
false
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_perameters, if: :devise_controller?


  protected

def authenticate_admin!
  authenticate_user!
  redirect_to 'pages/not_here', status: :forbidden unless current_user.admin?
end



   def email_required?
        false
   end

  def configure_permitted_perameters
    # devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:email, :password, :name, :id_number)}
    devise_parameter_sanitizer.permit(:sign_up){|u| u.permit(:identity, :name, :password, :id_number, :email) }

    devise_parameter_sanitizer.permit(:sign_in) {|u| u.permit(:identity, :email, :password, :name, :id_number)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit( :identity, :email, :password, :password_confirmation, :current_password, :id_number,:admin)}
  end

end

app/controllers/covid_forms_controller.rb
class CovidFormsController < ApplicationController

  def new
    @user = current_user
    @form = CovidForm.new
  end

  def create
    @user = current_user
    @covid_form = CovidForm.new(covid_form_params)
    # video = Cloudinary::Uploader.upload(params[:video], :resource_type => :video)
    # @item = covid_form.create!(video: video["url"], title: @covid_form.title, brief_id: @covid_form.brief_id)
    # @covid_form.user_id = current_user.id

    if @covid_form.save


      if (not @covid_form.cough?) && (not @covid_form.fever? )&& (not @covid_form.sense_of_taste?) && (not @covid_form.sense_of_smell?) && (not @covid_form.shortness_of_breath?) && (not @covid_form.past_two_weeks?) && (not @covid_form.sore_throat?) && (not @covid_form.awaiting_results?) && (not @covid_form.temp > 36.8)
        @logdate = LogDate.create!(date: @covid_form.date, user_id: @user.id)
        @flag = Flag.create!(status: "Clear", user_id: @user.id, log_date_id: @logdate.id, date: @covid_form.date, covid_form_id: @covid_form.id )
        redirect_to covid_form_path(@covid_form)
      else
        @logdate = LogDate.create!(date: @covid_form.date, user_id: @user.id)
        @flag = Flag.create!(status: "Flagged", user_id: @user.id, log_date_id: @logdate.id,  date: @covid_form.date, covid_form_id: @covid_form.id )
        redirect_to covid_form_path(@covid_form)
      end

      # render json: item
    else
      render :new
    end
  end

def show
  @user = current_user
  @form = CovidForm.find(params[:id])

end
    private

  def covid_form_params
    params.require(:covid_form).permit(:user_id, :sore_throat, :shortness_of_breath, :sense_of_taste, :sense_of_taste, :cough, :awaiting_results, :past_two_weeks, :fever, :temp, :date, :status)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @user = current_user
    @covid_forms = CovidForm.where(user_id: @user.id)

  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
end

app/controllers/log_dates_controller.rb
class LogDatesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!
    before_action :authenticate_admin!, only: [:team_records] # `only` part if applicable


  def home
    @user = current_user
    @drinks = Drink.all
  end



    def not_here
      @user= current_user
       @drinks = Drink.all
    end


    def team_records
      @user= current_user
       @drinks = Drink.all
       @flags = Flag.all
       @flags_with_dates = @flags.group_by{|flag| flag.date}


      end


private

  def authenticate_admin!
  authenticate_user!
  redirect_to "not_here", status: :forbidden unless current_user.admin?
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/covid_forms/new.html.erb
<div class= "container">

  <div class="row" style="margin-top: 56px; ">
    <div class="col-8 " style="position: relative; margin:0 auto; color: #20619C;">

    <h2 style="margin-bottom:56px;"> Place a <i class="fas fa-check"  style="padding-right: 20px; padding-left: 20px;"></i> in the boxes that describe your symptoms. Leave the box empty if you do not have that symptom. </h2>
    </div>



<div class="col-8" style="position: relative;margin:0 auto;">
<h1 style="padding-bottom: 40px;">My Symptoms</h1>
              <%= simple_form_for [@form] do |f| %>
              <div class="form_inputs">
              <div class="d-flex" style="justify-content: space-between;">
                  <p style="color:#black; font-size: 1.5rem;"> I have a Cough</p>
                  <%= f.check_box :cough, label: "Cough", class: "big-box form-l"%>
                </div>
                                <div class="d-flex" style="justify-content: space-between;">
                  <p style="color:#black; font-size: 1.5rem;"> I have a Fever</p>
                  <%= f.check_box :fever, label: "Cough", class: "big-box"%>
                </div>
                                <div class="d-flex" style="justify-content: space-between;">
                  <p style="color:#black; font-size: 1.5rem;"> Loss of sense of smell</p>
                  <%= f.check_box :sense_of_smell, label: "Cough", class: "big-box"%>
                </div>

                              <div class="d-flex" style="justify-content: space-between;">
                  <p style="color:#black; font-size: 1.5rem;"> Loss of sense of taste</p>
                  <%= f.check_box :sense_of_taste, label: "Cough", class: "big-box"%>
                </div>

                                <div class="d-flex" style="justify-content: space-between;">
                  <p style="color:#black; font-size: 1.5rem;"> I have a Sore throat</p>
                  <%= f.check_box :sore_throat, label: "Cough", class: "big-box"%>
                </div>

                                <div class="d-flex" style="justify-content: space-between;">
                  <p style="color:#black; font-size: 1.5rem;"> I am Awaiting the  Results of a covid test</p>
                  <%= f.check_box :awaiting_results, label: "Cough", class: "big-box"%>
                </div>

                                <div class="d-flex" style="justify-content: space-between;">
                                  <div class="col-8 " style="margin-left: -16px;">

                  <p style="color:#black; font-size: 1.5rem;"> I had contact with someone who tested positive for Covid-19 in the last 2 weeks</p>
                                  </div>
                                  <div class="mt-3">

                  <%= f.check_box :past_two_weeks, label: "Cough", class: "big-box-pad"%>
                                  </div>
                </div>

                                <div class="d-flex" style="justify-content: space-between;">
                  <p style="color:#black; font-size: 1.5rem;"> Shortness of Breath</p>
                  <%= f.check_box :shortness_of_breath, label: "Cough", class: "big-box"%>
                </div>

                                <div class="d-flex" style="justify-content: space-between;">
                  <%= f.hidden_field :user_id, value: @user.id%>
                </div>

                              <div class="d-flex" style="justify-content: space-between;">
                  <%= f.input :temp, label: "Temperature", class: "big-box"%>
                </div>


                        <div class="d-flex" style="justify-content: space-between;">
                  <%= f.input :date, label: "Date", class: "big-box"%>
                </div>
        <%= f.button :submit, class: "btn btn-flat-raiders my-5", value: "Submit Form" %>
<% end %>

            </div>


</div>

  </div>

          </div>

app/views/covid_forms/show.html.erb
<div class= "container">

  <div class="row" style="margin-top: 56px; ">

<div class="col-8" style="">

        <h2 style="margin-bottom:24px;">Date: <%= @form.date %> </h2>
        <% if @user == @form.user %>
    <h2 style="margin-bottom:56px;">Player Name: <%= @user.name.capitalize %> </h2>
    <% else %>

        <h2 style="margin-bottom:56px;">Player Name: <%= @form.user.name.capitalize %> </h2>

        <% end %>

</div>


<div class="col-12">
<h2 class="my-5" style="font-size:2.5rem; color:#266299;">The player is presenting the following symptoms:</h2>

   <% if @form.temp? %><div class=" col-6 d-flex my-5"style= "justify-content: space-between;">

                  <h2 style="margin-left: -20px;">Temperature:</h2>
                    <h3 style="color:black;"> <%= @form.temp %> degrees celcius</h3>
   </div>
                  <% end %>
                <% if @form.cough? %>
              <div class="" style="">
                  <h3 style="color:black;"> Cough</h3>
                </div>

                <% end %>

                <% if @form.fever? %>
                <div class="" style="">
                  <h3 style="color:black;"> Fever</h3>
                </div>
                <% end %>


                <% if @form.sense_of_smell? %>
                  <div class="" style="">
                  <h3 style="color:black;"> Loss of sense of smell</h3>
                </div>

                <% end %>


                <% if @form.sense_of_taste? %>
                              <div class="" style="">
                  <h3 style="color:black;"> Loss of sense of taste</h3>
                </div>

                <% end %>

                <% if @form.sore_throat? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Sore throat</h3>
                </div>

                <% end %>

                  <% if @form.awaiting_results? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Awaiting Results of a covid test</h3>
                </div>

                  <% end %>



                  <% if @form.past_two_weeks? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Been in contact in the last 2 weeks</h3>
                </div>

                  <% end %>

                <% if @form.shortness_of_breath? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Shortness of Breath</h3>
                </div>

                  <% end %>



</div>

<!-- <div class="col-12">
<h2 class="my-5" style="font-size:2.5rem; color:#266299;">The player is not presenting the following symptoms:</h2>

     <% if not @form.temp? %>
                  <h2>Temperature:</h2>
                    <h3 style="color:black;"> <%= @form.temp %> degrees celcius</h3>
                  <% end %>
                <% if not @form.cough? %>
              <div class="" style="">
                  <h3 style="color:black;"> Cough</h3>
                </div>

                <% end %>

                <% if not @form.fever? %>
                <div class="" style="">
                  <h3 style="color:black;"> Fever</h3>
                </div>
                <% end %>


                <% if not @form.sense_of_smell? %>
                  <div class="" style="">
                  <h3 style="color:black;"> Loss of sense of smell</h3>
                </div>

                <% end %>


                <% if not @form.sense_of_taste? %>
                              <div class="" style="">
                  <h3 style="color:black;"> Loss of sense of taste</h3>
                </div>

                <% end %>

                <% if not @form.sore_throat? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Sore throat</h3>
                </div>

                <% end %>

                  <% if not @form.awaiting_results? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Awaiting Results of a covid test</h3>
                </div>

                  <% end %>



                  <% if not @form.past_two_weeks? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Been in contact in the last 2 weeks</h3>
                </div>

                  <% end %>

                <% if not @form.shortness_of_breath? %>
                                <div class="" style="">
                  <h3 style="color:black;"> Shortness of Breath</h3>
                </div>

                  <% end %>
</div> -->
  </div>

          </div>

app/views/dashboards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-8">

      <h3 style="padding-top: 40px;"> Past forms for <%= @user.name %></h3>
      <div>
        <% @covid_forms.each do |form| %>
        <%= link_to covid_form_path(form) do %>
       <p> <%= form.date %></p>
       <% end %>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raiders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>
<div class="wrapper">

    <%= render 'shared/nav' %>
    <%= render 'shared/flashes' %>

  <body>
    <%= yield %>
  </body>


</div>
      <%= render 'shared/footer' %>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row" style="padding-top:164px;">
        <div class=" col-12 col-lg-8 fill" style="position: relative; margin: 0 auto;">
<%= image_tag "raiders.png" %>

    </div>
<% if user_signed_in? %>
<div class="col-12">
  <p style="text-align: center; padding-left:56px; font-size:1.5rem; margin-bottom: -32px; margin-top: 40px;">Tap the button to fill out your covid form</p>

 <p style="position: relative; margin:0 auto; text-align: center; padding-top: 56px; font-size:2.0rem; padding-left:56px;">    <%= link_to "Covid Form", new_covid_form_path, class: "btn-flat-raiders-gold" %>  </p>
</div>
<% else %>
      <div class="col-12" style="position: relative; margin: 0 auto;">
      <p style="text-align:center; padding-top:48px; padding-bottom: 48px; font-size:2.0rem; font-weight:700; padding-left:64px; ">Sign up or Login to fill out your covid form</p>
    </div>
<% end %>
  </div>
</div>

app/views/pages/not.html.erb
<h3>You are not authorized to view these records. make Your way back to the forms</h3>

app/views/pages/not_here.html.erb
<h3>You are not authorized to view these records. make Your way back to the forms</h3>

app/views/pages/team_records.html.erb
<div class="container">
  <div class="row">
    <div class="col-12" style="margin:0 auto; position: relative;">

      <h1 class="my-5"> Below is the list of players that were flagged on a particular day. you can view the symptoms they presented by clicking "View Form"</h1>
    </div>
    <div class="col-8">
<% @flags_with_dates.each do |key, array| %>


  <p style="font-weight:700; font-size: 1.5rem;"> <%= key %>  </p>
        <% array.each do |flag| %>
<div class= "d-flex" style="justify-content: space-between;">
        <p> <%= flag.user.name %> </p>
        <%= link_to "View Form", covid_form_path(flag.covid_form_id) %>
</div>
        <% end %>

<% end %>
</div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/raiders_rugbysa/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a>

    <a href="https://www.facebook.com/raidersrugbysa/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/raiders_rugbysa?lang=en"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i style="font-size: 1.75rem; font-weight:700; color: black">Producing the Springboks of tomorrow</i>
  </div>
</div>

app/views/shared/_nav.html.erb
<% if user_signed_in? %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logo.jpeg" %>
   <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="d-flex" style="justify-content: space-between;">
      <p class="navbar-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </p>
      <p class="nav-item active">
        <%= link_to "My Records", dashboards_show_path, class: "nav-link" %>
      </p>

      <% if current_user.admin? %>
            <p class="navbar-item">
        <%= link_to "Team Records", pages_team_records_path, class: "nav-link" %>
      </p>

      <% end %>


    <li class="nav-item dropdown" style="list-style-type: none;">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
  </div>
</div>
<% else %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logo.jpeg" %>
   <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="d-flex" style="justify-content: space-between;">
      <p class="navbar-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </p>
      <p class="nav-item active">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </p>
      <p class="nav-item active">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </p>
  </div>
</div>
<% end %>